FROM opensuse-15.0:latest
MAINTAINER Nathan Cutler <ncutler@suse.com>

RUN useradd -m jenkins
RUN  echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
COPY bashrc /home/jenkins/.bashrc
COPY deepsea /home/jenkins/DeepSea
RUN chown -R jenkins: /home/jenkins

USER jenkins

WORKDIR /home/jenkins

RUN echo %_topdir $HOME/rpmbuild | tee $HOME/.rpmmacros
RUN pwd && ls -la && cd DeepSea \
    && sudo zypper --non-interactive install --no-recommends \
           $(rpmspec --requires -q deepsea.spec.in 2>/dev/null)
RUN cd DeepSea && make rpm

#RUN mkdir repo && cp rpmbuild/RPMS/noarch/* repo && createrepo --repo deepsea_testing repo
#RUN sudo zypper addrepo $PWD/repo deepsea
#RUN sudo zypper --non-interactive --no-gpg-checks install deepsea deepsea-qa deepsea-cli

RUN sudo zypper --non-interactive --no-gpg-checks install rpmbuild/RPMS/*/*.rpm

RUN source /home/jenkins/.bashrc \
    && deepsea --version
