FROM opensuse-15.1:latest
MAINTAINER Nathan Cutler <ncutler@suse.com>
ARG usr=jenkins
RUN useradd -m $usr
RUN  echo "$usr ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
COPY bashrc /home/$usr/.bashrc
COPY deepsea /home/$usr/DeepSea
RUN chown -R $usr: /home/$usr

USER $usr

WORKDIR /home/$usr

RUN echo %_topdir $HOME/rpmbuild | tee $HOME/.rpmmacros
RUN pwd && ls -la && cd DeepSea \
    && sudo zypper --non-interactive --gpg-auto-import-keys refresh \
    && sudo zypper --non-interactive install --no-recommends \
           $(rpmspec --buildrequires -q deepsea.spec.in 2>/dev/null)
RUN cd DeepSea && make rpm

#RUN mkdir repo && cp rpmbuild/RPMS/noarch/* repo && createrepo --repo deepsea_testing repo
#RUN sudo zypper addrepo $PWD/repo deepsea
#RUN sudo zypper --non-interactive --no-gpg-checks install deepsea deepsea-qa deepsea-cli

RUN sudo zypper --non-interactive --no-gpg-checks install rpmbuild/RPMS/*/*.rpm

RUN source /home/$usr/.bashrc \
    && deepsea --version
