#!/bin/bash

function yj () {
    python -c "import json, yaml, sys ; d = yaml.safe_load(sys.stdin) ; json.dump(d,sys.stdout, indent=2)"
}
function jy() {
    python -c "import json, yaml, sys ; d = json.load(sys.stdin) ; yaml.safe_dump(d,sys.stdout, default_flow_style=False)"
}

function to_xml() {
    python -c "import sys; from xml.dom.minidom import Text ; \
        t = Text() ; t.data = sys.stdin.read() ; \
        print(t.toxml())"
}
